##spring은 이 파일은 무조건 읽는다. 그 뒤 dev환경인지 test환경인지 검사한 후 -dev, -test로 오버라이딩한다.
server:
  port: 8070

spring:
  application:
    name: p-62-260730
  profiles:
    active: dev

  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE